name: certora

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check key
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: echo "key length" ${#CERTORAKEY}

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip install certora-cli

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17

      - name: Verify rule ${{ matrix.rule }}
        run: |
          cd certora
          touch applyHarness.patch
          make munged
          cd ..
          echo "key length" ${#CERTORAKEY}
          certoraRun certora/conf/${{ matrix.rule }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        rule:
          - runPropertiesWithSummarization.conf --send_only --rule allSharesAreBacked
          - runInvariants.conf --send_only --rule cooldownDataCorrectness
          - runInvariants.conf --send_only --rule cooldownAmountNotGreaterThanBalance
          - runInvariants.conf --send_only --rule lowerBoundNotZero
          - runInvariants.conf --send_only --rule balanceOfZero
          - runInvariants.conf --send_only --rule totalSupplyGreaterThanUserBalance
          - runInvariants.conf --send_only --rule PersonalIndexLessOrEqualGlobalIndex
          - runAllProps.conf --send_only --rule integrityOfStaking
          - runAllProps.conf --send_only --rule previewStakeEquivalentStake
          - runAllProps.conf --send_only --rule noStakingPostSlashingPeriod
          - runAllProps.conf --send_only --rule cooldownCorrectness
          - runAllProps.conf --send_only --rule integrityOfRedeem
          - runAllProps.conf --send_only --rule noRedeemOutOfUnstakeWindow
          - runAllProps.conf --send_only --rule integrityOfSlashing
          - runAllProps.conf --send_only --rule noSlashingMoreThanMax
          - runAllProps.conf --send_only --rule noEntryUntilSlashingSettled
          - runAllProps.conf --send_only --rule slashingIncreaseExchangeRate
          - runAllProps.conf --send_only --rule slashAndReturnFundsOfZeroDoesntChangeExchangeRate
          - runAllProps.conf --send_only --rule integrityOfReturnFunds
          - runAllProps.conf --send_only --rule returnFundsDecreaseExchangeRate
          - runAllProps.conf --send_only --rule rewardsGetterEquivalentClaim
          - runAllProps.conf --send_only --rule rewardsMonotonicallyIncrease
          - runAllProps.conf --send_only --rule rewardsIncreaseForNonClaimFunctions
          - runAllProps.conf --send_only --rule totalSupplyDoesNotDropToZero
          - runAllProps.conf --send_only --rule exchangeRateNeverZero
          - runAllProps.conf --send_only --rule airdropNotMutualized
          - runAllProps.conf --send_only --rule indexesMonotonicallyIncrease
