name: certora

on:
  push:
    branches:
      - main
      - certora
  pull_request:
    branches:
      - main
      - ted_rules

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check key
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: echo "key length" ${#CERTORAKEY}
      
      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip install certora-cli
        
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.17
      
      - name: Verify rule ${{ matrix.rule }}
        run: |
          cd certora
          touch applyHarness.patch
          make munged
          cd ..
          echo "key length" ${#CERTORAKEY}
          sh certora/scripts/${{ matrix.rule }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
          
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        rule:
          - runPropertiesWithSummarization.sh allSharesAreBacked
          - runPropertiesWithSummarization.sh allStakedAaveBacked
          - runInvariants.sh exchangeRateCorrectness
          - runInvariants.sh balanceOfZero
          - runInvariants.sh cooldownDataCorrectness
          - runInvariants.sh cooldownAmountNotGreaterThanBalance
          - runInvariants.sh totalSupplyGreaterThanUserBalance
          - runInvariants.sh PersonalIndexLessOrEqualGlobalIndex
          - runInvariants.sh allSharesAreBacked
          - runAllProps.sh integrityOfStaking
          - runAllProps.sh noStakingPostSlashingPeriod
          - runAllProps.sh noSlashingMoreThanMax
          - runAllProps.sh integrityOfSlashing
          - runAllProps.sh integrityOfReturnFunds
          - runAllProps.sh noEntryUntilSlashingSettled
          - runAllProps.sh airdropNotMutualized
          - runAllProps.sh noRedeemOutOfUnstakeWindow
          - runAllProps.sh integrityOfRedeem
          - runAllProps.sh cooldownCorrectness
          - runAllProps.sh rewardsGetterEquivalentClaim
          - runAllProps.sh rewardsMonotonicallyIncrease
          - runAllProps.sh rewardsIsNonZero
          - runAllProps.sh collectedRewardsMonotonicallyIncrease
          - runAllProps.sh indexesMonotonicallyIncrease
          - runAllProps.sh slashingIncreaseExchangeRate
          - runAllProps.sh returnFundsDecreaseExchangeRate
          - runAllProps.sh exchangeRateNeverZero
          - runAllProps.sh slashAndReturnFundsOfZeroDoesntChangeExchangeRate
          - runAllProps.sh previewRedeemEquivalentRedeem
          - runAllProps.sh previewStakeEquivalentStake
